version: '3.7'
services:
  db:
    build: ./db
    networks:
      - prod
    environment:
      DB: jeopardy
      PGDATA: /jeopardy-db-data
      POSTGRES_DB: jeopardy
      DBPASSWORD: ${DBPASSWORD}


    volumes:
      - db-data-prod:/jeopardy-db-data

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: prod
    networks: [prod]
    init: true
    restart: unless-stopped
    environment:
      DBPASSWORD: ${DBPASSWORD}
      PORT: 80

    entrypoint: ["/app/bin/jeopardy"]
    command: ["foreground"]


  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: prod
    networks: [prod]

networks:
  prod:

volumes:
  db-data-prod:
